import React from 'react';
import { useSelector } from 'react-redux';
import Link from 'next/link';

export default function CardProduct({ id, name, types, abilities }) {
  
  const { state } = useSelector(state => state.bgTheme);

  return (

    <Link href={`/product/${id}`} >

      <div className={`rounded-lg shadow-lg p-4 m-5 h-24 transition delay-200 hover:cursor-pointer hover:scale-110 hover:-rotate-12 ${state ? 'bg-light-bgCard' : 'bg-dark-bgCard'}`}>

        <h2 className="text-2xl font-semibold">{String(name).toLocaleUpperCase()}</h2>

        { abilities?.length > 0 && <p className="text-gray-600 text-lg font-bold">Habilidades: {abilities?.length}</p> }

      </div>

    </Link>

  );

};

export async function getServerSideProps() {
  // Lógica para obtener metadata
  const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  };

  // Devolver los props
  return {
    props: {
      metadata,
    },
  };
}